// module.exports.chainData = {
//     akash: {
//         id: 0,
//         name: "akash",
//         api: "https://backend.notional.ventures/akash",
//         rpc_service: "https://rpc-akash-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-akash-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-akash-ia.cosmosia.notional.ventures/",
//         address: "akash1083svrca4t350mphfv9x45wq9asrs60c956m2m",
//         hexAddr: "3E6DCCBF15DF0F142283689333B4991C81C08402",
//         prefixValCons: "akashvalcons",
//         ping: "akash-network",
//         mintscan: "akash",
//     },
//     bitsong: {
//         id: 2,
//         image: "/images/chain-logo/bitsong.png",
//         name: "bitsong",
//         api: "https://backend.notional.ventures/bitsong",
//         rpc_service: "https://rpc-bitsong-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-bitsong-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-bitsong-ia.cosmosia.notional.ventures/",
//         address: "bitsong1je872m97uce2ttztkh8pdx6zezw5kr03vkdke5",
//         hexAddr: "DC9ABBE8E5A7335D81A8E7BDA91D7B0EA32C823D",
//         prefixValCons: "bitsongvalcons",
//         ping: "bitsong",
//         mintscan: "bitsong",
//     },
//     bitcanna: {
//         id: 3,
//         image: "/images/chain-logo/bitcanna.png",
//         name: "bitcanna",
//         api: "https://backend.notional.ventures/bitcanna",
//         rpc_service: "https://rpc-bitcanna-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-bitcanna-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-bitcanna-ia.cosmosia.notional.ventures/",
//         address: "bcna1dl7w3myyfmnarh0t5uxmy7qe6szagz3ka2nq42",
//         hexAddr: "bcnavalcons",
//         prefixValCons: "A2D63B4BF7173AFA379D5D5B10A9B9535858B1E3",
//         ping: "bitcanna",
//         mintscan: "bitcanna",
//     },
//     : {
//         id: 4,
//         image: "/images/chain-logo/cosmos.png",
//         name: "atom",
//         api: "https://backend.notional.ventures/gaia",
//         rpc_service: "https://rpc-cosmoshub-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-cosmoshub-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-cosmoshub-ia.cosmosia.notional.ventures/",
//         address: "cosmos1083svrca4t350mphfv9x45wq9asrs60cg0hunp",
//         hexAddr: "1BB296700D6FCF2318AADA2D098E4D40479B6C7E",
//         prefixValCons: "cosmosvalcons",
//         ping: "cosmos",
//         mintscan: "cosmos",
//     },
//     cheq: {
//         id: 5,
//         image: "/images/chain-logo/cheq.png",
//         name: "cheq",
//         api: "https://backend.notional.ventures/cheq",
//         rpc_service: "https://rpc-cheqd-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-cheqd-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-cheqd-ia.cosmosia.notional.ventures/",
//         address: "cheqd1gyjqlfkrggd0uyd748fw9y5kq9xzmjqqgdenpy",
//         hexAddr: "82F41AEAE0AC7A81B2A130F9B62CBEFF1C620905",
//         prefixValCons: "cheqdvalcons",
//         ping: "cheqd-network",
//         mintscan: "cheqd",
//     },
//     chihuahua: {
//         id: 6,
//         image: "/images/chain-logo/chihuahua.png",
//         name: "chihuahua",
//         api: "https://backend.notional.ventures/chihuahua",
//         rpc_service: "https://rpc-chihuahua-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-chihuahua-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-chihuahua-ia.cosmosia.notional.ventures/",
//         address: "chihuahua1h6vcu4r2hx70x5f0l3du3ey2g98u9ut2c2fwqs",
//         hexAddr: "C13AC76E729A4408F13A935220B1D5A674AD55CD",
//         prefixValCons: "chihuahuavalcons",
//         ping: "chihuahua-token",
//         mintscan: "chihuahua",
//     },
//     cyber: {
//         id: 7,
//         image: "/images/chain-logo/cyber.png",
//         name: "cyber",
//         api: "https://backend.notional.ventures/cyber",
//         rpc_service: "https://rpc-cyber-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-cyber-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-cyber-ia.cosmosia.notional.ventures/",
//         address: "bostrom1g65rmjkeuy5rywx04s4fvwfylmlz98vqdj9qrh",
//         hexAddr: "0A7031E4F154F332A2462643CFC65C244A44712B",
//         prefixValCons: "bostromvalcons",
//         ping: "bostrom",
//         mintscan: "bostrom",
//     },
//     "e-money": {
//         id: 8,
//         image: "/images/chain-logo/emoney.png",
//         name: "e-money",
//         api: "https://backend.notional.ventures/emoney",
//         rpc_service: "https://rpc-emoney-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-emoney-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-emoney-ia.cosmosia.notional.ventures/",
//         address: "emoney16dc379m0qj64g4pr4nkl7ewak52qy2srxeutcv",
//         hexAddr: "0F582D2C490BE99DF9D11AF4335567861700C0B8",
//         prefixValCons: "emoneyvalcons",
//         ping: "e-money",
//         mintscan: "emoney",
//     },
//     evmos: {
//         id: 9,
//         image: "/images/chain-logo/evmos.png",
//         name: "evmos",
//         api: "https://backend.notional.ventures/evmos",
//         rpc_service: "https://rpc-evmos-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-evmos-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-evmos-ia.cosmosia.notional.ventures/",
//         address: "evmos1rv94jqhlhx6makfwl6qs390e4shg32m6r5zkre",
//         hexAddr: "FBC7E15255A18264C3AF14712F3C6A444B2412AF",
//         prefixValCons: "evmosvalcons",
//         ping: "evmos",
//         mintscan: "evmos",
//     },
//     "fetch.AI": {
//         id: 10,
//         image: "/images/chain-logo/fetch.png",
//         name: "fetch.AI",
//         api: "https://backend.notional.ventures/fetch",
//         rpc_service: "https://rpc-fetchhub-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-fetchhub-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-fetchhub-ia.cosmosia.notional.ventures/",
//         address: "fetch1s9myentgxavnpw7648an2v6zvvpza0axc7jwup",
//         hexAddr: "3F0677A345CBE77FBC9EF769371710B70AD73F86",
//         prefixValCons: "fetchvalcons",
//         ping: "fetch-ai",
//         mintscan: "fetchai",
//     },
//     injective: {
//         id: 11,
//         image: "/images/chain-logo/injective.png",
//         name: "injective",
//         api: "https://backend.notional.ventures/injective",
//         rpc_service: "https://rpc-injective-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-injective-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-injective-ia.cosmosia.notional.ventures/",
//         address: "inj16eg6wf2k6v0lzwu2vsrhxhe0tcycgr7jvrjk9x",
//         hexAddr: "CC8D91AE72CD6156C5064524B4BDADC97405DCC7",
//         prefixValCons: "injvalcons",
//         ping: "injective-protocol",
//         mintscan: "injective",
//     },
//     ixo: {
//         id: 12,
//         image: "/images/chain-logo/ixo.png",
//         name: "ixo",
//         api: "https://backend.notional.ventures/ixo",
//         rpc_service: "https://rpc-ixo-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-ixo-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-ixo-ia.cosmosia.notional.ventures/",
//         address: "ixo1083svrca4t350mphfv9x45wq9asrs60ch6fwhj",
//         hexAddr: "33E702E0A42967702B5D4319A26DB86BA0A99313",
//         prefixValCons: "ixovalcons",
//         ping: "ixo",
//         mintscan: "ixo",
//     },
//     juno: {
//         id: 13,
//         image: "/images/chain-logo/juno.png",
//         name: "juno",
//         api: "https://backend.notional.ventures/juno",
//         rpc_service: "https://rpc-juno-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-juno-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-juno-ia.cosmosia.notional.ventures/",
//         address: "juno1083svrca4t350mphfv9x45wq9asrs60c7a585a",
//         hexAddr: "6EC804DBB72380D0AA5AC6A82650A1FA75FBABC5",
//         prefixValCons: "junovalcons",
//         ping: "juno-network",
//         mintscan: "juno",
//     },
//     kava: {
//         id: 14,
//         image: "/images/chain-logo/kava.png",
//         name: "kava",
//         api: "https://backend.notional.ventures/kava",
//         rpc_service: "https://rpc-kava-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-kava-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-kava-ia.cosmosia.notional.ventures/",
//         address: "kava13jyqfhak8mu4c7pydjm3eu4qla7g06a93vupll",
//         hexAddr: "B4B7B3C8EF127B42F94B1260F7633CE20FC9020B",
//         prefixValCons: "kavavalcons",
//         ping: "kava",
//         mintscan: "kava",
//     },
//     kichain: {
//         id: 15,
//         image: "/images/chain-logo/ki.png",
//         name: "kichain",
//         api: "https://backend.notional.ventures/ki",
//         rpc_service: "https://rpc-kichain-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-kichain-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-kichain-ia.cosmosia.notional.ventures/",
//         address: "ki1lmkzaxztjpesh0mf7qy76l5npqwc7fk3tdcfak",
//         hexAddr: "D3A696E87669E124AE4A3614ACB83B8618F37829",
//         prefixValCons: "kivalcons",
//         ping: "ki",
//         mintscan: "ki-chain",
//     },
//     konstellation: {
//         id: 16,
//         image: "/images/chain-logo/konstellation.png",
//         name: "konstellation",
//         api: "https://backend.notional.ventures/konstellation",
//         rpc_service: "https://rpc-konstellation-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-konstellation-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-konstellation-ia.cosmosia.notional.ventures/",
//         address: "darc1fndgrsqmmq68ppl42wjkxh32nwpuj7vq6vfxa0",
//         hexAddr: "E1E4D63E42899583CA2A65E4C4DD69F8DD53F784",
//         prefixValCons: "darcvalcons",
//         ping: "konstellation",
//         mintscan: "konstellation",
//     },
//     osmosis: {
//         id: 18,
//         image: "/images/chain-logo/osmosis.png",
//         name: "osmosis",
//         api: "https://backend.notional.ventures/osmosis",
//         rpc_service: "https://rpc-osmosis-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-osmosis-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-osmosis-ia.cosmosia.notional.ventures/",
//         address: "osmo1083svrca4t350mphfv9x45wq9asrs60cq5yv9n",
//         hexAddr: "D9EC9739CCCF051A05861ACB8A2218A9A4756390",
//         prefixValCons: "osmovalcons",
//         ping: "osmosis",
//         mintscan: "osmosis",
//     },
//     omniflix: {
//         id: 19,
//         image: "/images/chain-logo/omniflix.png",
//         name: "omniflix",
//         api: "https://backend.notional.ventures/flix",
//         rpc_service: "https://rpc-omniflixhub-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-omniflixhub-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-omniflixhub-ia.cosmosia.notional.ventures/",
//         address: "omniflix15wshq6lmxmcn9vxky2mxf8zhstpn9ywmy2xhcu",
//         hexAddr: "2E530AEF6EF9B4497560EE670AD2F4996486BF98",
//         prefixValCons: "omniflixvalcons",
//         ping: "omniflix-network",
//         mintscan: "omniflix",
//     },
//     passage: {
//         id: 20,
//         image: "/images/chain-logo/passage.png",
//         name: "passage",
//         api: "https://backend.notional.ventures/passage",
//         rpc_service: "https://rpc-passage-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-passage-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-passage-ia.cosmosia.notional.ventures/",
//         address: "pasg14npnd73z5qjwz4az2dpw6vcdvkj29qg0t5ht5w",
//         hexAddr: "AF129E73E9CC68AD9A18F42973C5CA6CB6CC8F7B",
//         prefixValCons: "pasgvalcons",
//         ping: "passage",
//         mintscan: "passage",
//     },
//     provenance: {
//         id: 21,
//         image: "/images/chain-logo/pro.png",
//         name: "provenance",
//         api: "https://backend.notional.ventures/provenance",
//         rpc_service: "https://rpc-provenance-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-provenance-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-provenance-ia.cosmosia.notional.ventures/",
//         address: "pb10ap9fj9uq50cardmlzdj367kqg5x3ghjzkxumm",
//         hexAddr: "66DC6ACB190AA67582334077A8E984B2845A1EE3",
//         prefixValCons: "pbvalcons",
//         ping: "provenance-blockchain",
//         mintscan: "provenance",
//     },
//     regen: {
//         id: 22,
//         image: "/images/chain-logo/regen.png",
//         name: "regen",
//         api: "https://backend.notional.ventures/regen",
//         rpc_service: "https://rpc-regen-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-regen-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-regen-ia.cosmosia.notional.ventures/",
//         address: "regen1083svrca4t350mphfv9x45wq9asrs60chduq99",
//         hexAddr: "BA224E5B13AD05AAA86A2ECA876CB823D6388372",
//         prefixValCons: "regenvalcons",
//         ping: "regen",
//         mintscan: "regen",
//     },
//     sifchain: {
//         id: 23,
//         image: "/images/chain-logo/sifchain.png",
//         name: "sifchain",
//         api: "https://backend.notional.ventures/sif",
//         rpc_service: "https://rpc-sifchain-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-sifchain-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-sifchain-ia.cosmosia.notional.ventures/",
//         address: "sif1083svrca4t350mphfv9x45wq9asrs60cdjc2u2",
//         hexAddr: "",
//         prefixValCons: "",
//         ping: "sifchain",
//         mintscan: "sifchain",
//     },
//     stargaze: {
//         id: 24,
//         image: "/images/chain-logo/stargaze.png",
//         name: "stargaze",
//         api: "https://backend.notional.ventures/stargaze",
//         rpc_service: "https://rpc-stargaze-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-stargaze-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-stargaze-ia.cosmosia.notional.ventures/",
//         address: "stars1v8yp5x5kfex4wep2pfuuyw68cn2lst3kmpmutg",
//         hexAddr: "EF4A8B7D36CAFB700A6B27453A78637CBA2B8B88",
//         prefixValCons: "starsvalcons",
//         ping: "stargaze",
//         mintscan: "stargaze",
//     },
//     starname: {
//         id: 25,
//         image: "/images/chain-logo/starname.png",
//         name: "starname",
//         api: "https://backend.notional.ventures/starname",
//         rpc_service: "https://rpc-starname-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-starname-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-starname-ia.cosmosia.notional.ventures/",
//         address: "star1pdqlmncych8uzsfdnsptv7s0wpazc0rgf4xgk7",
//         hexAddr: "A556774ABC39742ECF39A4228A4D759FE4D16E34",
//         prefixValCons: "starvalcons",
//         ping: "starname",
//         mintscan: "starname",
//     },
//     secret: {
//         id: 26,
//         image: "/images/chain-logo/secret.png",
//         name: "secret",
//         api: "https://backend.notional.ventures/secret",
//         rpc_service: "",
//         api_service: "",
//         grpc_service: "",
//         address: "secret18rchk5exp2vzcwrwuret5sjwpxhf4sq2m9hgq2",
//         hexAddr: "2188C75620C17533BA918E13CFF8957BE8EED9AD",
//         prefixValCons: "cosmosvalcons",
//         ping: "secret",
//         mintscan: "secret",
//     },
//     stride: {
//         id: 27,
//         image: "/images/chain-logo/stride.png",
//         name: "stride",
//         api: "https://backend.notional.ventures/stride",
//         address: "stride1kvwpcr45lh7wn53wp9ac42ypr3t8zjqyer5e3e",
//         api_service: "https://api-stride-ia.cosmosia.notional.ventures/",
//         hexAddr: "B570CB0B35A162B0B32E1F025232851458D1C41A",
//         prefixValCons: "stridevalcons",
//         ping: "stride",
//         mintscan: "stride",
//     },
//     sentinel: {
//         id: 28,
//         image: "/images/chain-logo/sentinel.png",
//         name: "sentinel",
//         api: "https://backend.notional.ventures/sentinel",
//         rpc_service: "https://rpc-stride-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-sentinel-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-stride-ia.cosmosia.notional.ventures/",
//         address: "sent1083svrca4t350mphfv9x45wq9asrs60cn5p9hw",
//         hexAddr: "ED26B871F6AC0554799B7D7D1124C19ED9A059A7",
//         prefixValCons: "sentvalcons",
//         ping: "sentinel",
//         mintscan: "sentinel",
//     },
//     umee: {
//         id: 29,
//         image: "/images/chain-logo/umee.png",
//         name: "umee",
//         api: "https://backend.notional.ventures/umee",
//         rpc_service: "https://rpc-umee-ia.cosmosia.notional.ventures/",
//         api_service: "https://api-umee-ia.cosmosia.notional.ventures/",
//         grpc_service: "https://grpc-umee-ia.cosmosia.notional.ventures/",
//         address: "umee1dmahqt84r9je3sqvljzjrttjj78cmrf39jndx6",
//         hexAddr: "2CB064741F8D8EE2C001EBADD557872266F5698C",
//         prefixValCons: "umeevalcons",
//         ping: "umee",
//         mintscan: "umee",
//     },
// };

module.exports.data = {
    'akash-validator': {
        id: 0,
        address: 'akash1083svrca4t350mphfv9x45wq9asrs60c956m2m',
        valAddr: 'akashvaloper1083svrca4t350mphfv9x45wq9asrs60c0k5a63',
        key: 'akash',
        name: 'akash-validator',
        rpc_service: "https://rpc-akash-ia.cosmosia.notional.ventures/",
        api_service: "https://api-akash-ia.cosmosia.notional.ventures/",
    },
    'atom-validator': {
        id: 4,
        address: 'cosmos1083svrca4t350mphfv9x45wq9asrs60cg0hunp',
        valAddr: 'cosmosvaloper1083svrca4t350mphfv9x45wq9asrs60cdmrflj',
        key: 'atom',
        name: 'atom-validator',
        rpc_service: "https://rpc-cosmoshub-ia.cosmosia.notional.ventures/",
        api_service: "https://api-cosmoshub-ia.cosmosia.notional.ventures/",
    },
    'bitsong-validator': {
        id: 2,
        address: 'bitsong1je872m97uce2ttztkh8pdx6zezw5kr03vkdke5',
        valAddr: 'bitsongvaloper1je872m97uce2ttztkh8pdx6zezw5kr03dj3lff',
        key: 'bitsong',
        name: 'bitsong-validator',
        rpc_service: "https://rpc-bitsong-ia.cosmosia.notional.ventures/",
        api_service: "https://api-bitsong-ia.cosmosia.notional.ventures/",
    },
    'bitcanna-validator': {
        id: 3,
        address: 'bcna1dl7w3myyfmnarh0t5uxmy7qe6szagz3ka2nq42',
        valAddr: 'bcnavaloper1dl7w3myyfmnarh0t5uxmy7qe6szagz3kyhzq07',
        key: 'bitcanna',
        name: 'bitcanna-validator',
        rpc_service: "https://rpc-bitcanna-ia.cosmosia.notional.ventures/",
        api_service: "https://api-bitcanna-ia.cosmosia.notional.ventures/",
    },
    'cheq-validator': {
        id: 5,
        address: 'cheqd1gyjqlfkrggd0uyd748fw9y5kq9xzmjqqgdenpy',
        valAddr: 'cheqdvaloper1gyjqlfkrggd0uyd748fw9y5kq9xzmjqqh8848x',
        key: 'cheq',
        name: 'cheq-validator',
        rpc_service: "https://rpc-cheqd-ia.cosmosia.notional.ventures/",
        api_service: "https://api-cheqd-ia.cosmosia.notional.ventures/",
    },
    'chihuahua-validator': {
        id: 6,
        address: 'chihuahua1h6vcu4r2hx70x5f0l3du3ey2g98u9ut2c2fwqs',
        valAddr: 'chihuahuavaloper1h6vcu4r2hx70x5f0l3du3ey2g98u9ut2tafnnv',
        key: 'chihuahua',
        name: 'chihuahua-validator',
        rpc_service: "https://rpc-chihuahua-ia.cosmosia.notional.ventures/",
        api_service: "https://api-chihuahua-ia.cosmosia.notional.ventures/",
    },
    'cyber-validator': {
        id: 7,
        address: 'bostrom1g65rmjkeuy5rywx04s4fvwfylmlz98vqdj9qrh',
        valAddr: 'bostromvaloper1g65rmjkeuy5rywx04s4fvwfylmlz98vq4gzln5',
        key: 'cyber',
        name: 'cyber-validator',
        rpc_service: "https://rpc-cyber-ia.cosmosia.notional.ventures/",
        api_service: "https://api-cyber-ia.cosmosia.notional.ventures/",
    },
    'emoney-validator': {
        id: 8,
        address: 'emoney16dc379m0qj64g4pr4nkl7ewak52qy2srxeutcv',
        valAddr: 'emoneyvaloper16dc379m0qj64g4pr4nkl7ewak52qy2srpe6lxp',
        key: 'e-money',
        name: 'emoney-validator',
        rpc_service: "https://rpc-emoney-ia.cosmosia.notional.ventures/",
        api_service: "https://api-emoney-ia.cosmosia.notional.ventures/",
    },
    'evmos-validator': {
        id: 9,
        address: 'evmos1rv94jqhlhx6makfwl6qs390e4shg32m6r5zkre',
        valAddr: 'evmosvaloper1rv94jqhlhx6makfwl6qs390e4shg32m6w6dxzy',
        key: 'evmos',
        name: 'evmos-validator',
        rpc_service: "https://rpc-evmos-ia.cosmosia.notional.ventures/",
        api_service: "https://api-evmos-ia.cosmosia.notional.ventures/",
    },
    'fetch.AI-validator': {
        id: 10,
        address: 'fetch1s9myentgxavnpw7648an2v6zvvpza0axc7jwup',
        valAddr: 'fetchvaloper1s9myentgxavnpw7648an2v6zvvpza0axa6dd0x',
        key: 'fetch.AI',
        name: 'fetch.AI-validator',
        rpc_service: "https://rpc-fetchhub-ia.cosmosia.notional.ventures/",
        api_service: "https://api-fetchhub-ia.cosmosia.notional.ventures/",
    },
    'injective-validator': {
        id: 11,
        address: 'inj16eg6wf2k6v0lzwu2vsrhxhe0tcycgr7jvrjk9x',
        valAddr: 'injvaloper16eg6wf2k6v0lzwu2vsrhxhe0tcycgr7jm98nyz',
        key: 'injective',
        name: 'injective-validator',
        rpc_service: "https://rpc-injective-ia.cosmosia.notional.ventures/",
        api_service: "https://api-injective-ia.cosmosia.notional.ventures/",
    },
    'ixo-validator': {
        id: 12,
        address: 'ixo1083svrca4t350mphfv9x45wq9asrs60ch6fwhj',
        valAddr: 'ixovaloper1083svrca4t350mphfv9x45wq9asrs60camel0h',
        key: 'ixo',
        name: 'ixo-validator',
        rpc_service: "https://rpc-ixo-ia.cosmosia.notional.ventures/",
        api_service: "https://api-ixo-ia.cosmosia.notional.ventures/",
    },
    'juno-validator': {
        id: 13,
        address: 'juno1083svrca4t350mphfv9x45wq9asrs60c7a585a',
        valAddr: 'junovaloper1083svrca4t350mphfv9x45wq9asrs60cpqzg0y',
        key: 'juno',
        name: 'juno-validator',
        rpc_service: "https://rpc-juno-ia.cosmosia.notional.ventures/",
        api_service: "https://api-juno-ia.cosmosia.notional.ventures/",
    },
    'kava-validator': {
        id: 14,
        address: 'kava13jyqfhak8mu4c7pydjm3eu4qla7g06a93vupll',
        valAddr: 'kavavaloper13jyqfhak8mu4c7pydjm3eu4qla7g06a9u6xf8g',
        key: 'kava',
        name: 'kava-validator',
        rpc_service: "https://rpc-kava-ia.cosmosia.notional.ventures/",
        api_service: "https://api-kava-ia.cosmosia.notional.ventures/",
    },
    'kichain-validator': {
        id: 15,
        address: 'ki1lmkzaxztjpesh0mf7qy76l5npqwc7fk3tdcfak',
        valAddr: 'kivaloper1lmkzaxztjpesh0mf7qy76l5npqwc7fk3l2k57g',
        key: 'kichain',
        name: 'kichain-validator',
        rpc_service: "https://rpc-kichain-ia.cosmosia.notional.ventures/",
        api_service: "https://api-kichain-ia.cosmosia.notional.ventures/",
    },
    'likecoin-validator': {
        id: 17,
        address: 'like16dc379m0qj64g4pr4nkl7ewak52qy2sr6x6av2',
        valAddr: 'likevaloper16dc379m0qj64g4pr4nkl7ewak52qy2srvfvrue',
        key: 'likecoin',
        name: 'likecoin-validator',
        rpc_service: "https://rpc-likecoin-ia.cosmosia.notional.ventures/",
        api_service: "https://api-likecoin-ia.cosmosia.notional.ventures/",
    },
    'osmosis-validator': {
        id: 18,
        address: 'osmo1083svrca4t350mphfv9x45wq9asrs60cq5yv9n',
        valAddr: 'osmovaloper1083svrca4t350mphfv9x45wq9asrs60c6rv0j5',
        key: 'osmosis',
        name: 'osmosis-validator',
        rpc_service: "https://rpc-osmosis-ia.cosmosia.notional.ventures/",
        api_service: "https://api-osmosis-ia.cosmosia.notional.ventures/",
    },
    'omniflix-validator': {
        id: 19,
        address: 'omniflix15wshq6lmxmcn9vxky2mxf8zhstpn9ywmy2xhcu',
        valAddr: 'omniflixvaloper15wshq6lmxmcn9vxky2mxf8zhstpn9ywmfc5ke5',
        key: 'omniflix',
        name: 'omniflix-validator',
        rpc_service: "https://rpc-omniflixhub-ia.cosmosia.notional.ventures/",
        api_service: "https://api-omniflixhub-ia.cosmosia.notional.ventures/",
    },
    'passage-validator': {
        id: 20,
        address: 'pasg14npnd73z5qjwz4az2dpw6vcdvkj29qg0t5ht5w',
        valAddr: 'pasgvaloper14npnd73z5qjwz4az2dpw6vcdvkj29qg0cgar4j',
        key: 'passage',
        name: 'passage-validator',
        rpc_service: "https://rpc-passage-ia.cosmosia.notional.ventures/",
        api_service: "https://api-passage-ia.cosmosia.notional.ventures/",
    },
    'provenance-validator': {
        id: 21,
        address: 'pb10ap9fj9uq50cardmlzdj367kqg5x3ghjzkxumm',
        valAddr: 'pbvaloper10ap9fj9uq50cardmlzdj367kqg5x3ghjdp2v6p',
        key: 'provenance',
        name: 'provenance-validator',
        rpc_service: "https://rpc-provenance-ia.cosmosia.notional.ventures/",
        api_service: "https://api-provenance-ia.cosmosia.notional.ventures/",
    },
    'regen-validator': {
        id: 22,
        address: 'regen1083svrca4t350mphfv9x45wq9asrs60chduq99',
        valAddr: 'regenvaloper1083svrca4t350mphfv9x45wq9asrs60ct2p9a5',
        key: 'regen',
        name: 'regen-validator',
        rpc_service: "https://rpc-regen-ia.cosmosia.notional.ventures/",
        api_service: "https://api-regen-ia.cosmosia.notional.ventures/",
    },
    'stargaze-validator': {
        id: 24,
        address: 'stars1v8yp5x5kfex4wep2pfuuyw68cn2lst3kmpmutg',
        valAddr: 'starsvaloper1v8yp5x5kfex4wep2pfuuyw68cn2lst3ksl0gss',
        key: 'stargaze',
        name: 'stargaze-validator',
        rpc_service: "https://rpc-stargaze-ia.cosmosia.notional.ventures/",
        api_service: "https://api-stargaze-ia.cosmosia.notional.ventures/",
    },
    'starname-validator': {
        id: 25,
        address: 'star1pdqlmncych8uzsfdnsptv7s0wpazc0rgf4xgk7',
        valAddr: 'starvaloper1pdqlmncych8uzsfdnsptv7s0wpazc0rgv7zc6h',
        key: 'starname',
        name: 'starname-validator',
        rpc_service: "https://rpc-starname-ia.cosmosia.notional.ventures/",
        api_service: "https://api-starname-ia.cosmosia.notional.ventures/",
    },
    'stride-validator': {
        id: 27,
        address: 'stride1kvwpcr45lh7wn53wp9ac42ypr3t8zjqyer5e3e',
        valAddr: 'stridevaloper1kvwpcr45lh7wn53wp9ac42ypr3t8zjqy6ks9au',
        key: 'stride',
        name: 'stride-validator',
        rpc_service: "https://rpc-stride-ia.cosmosia.notional.ventures/",
        api_service: "https://api-stride-ia.cosmosia.notional.ventures/",
    },
    'sentinel-validator': {
        id: 28,
        address: 'sent1083svrca4t350mphfv9x45wq9asrs60cn5p9hw',
        valAddr: 'sentvaloper1083svrca4t350mphfv9x45wq9asrs60cv37gc8',
        key: 'sentinel',
        name: 'sentinel-validator',
        rpc_service: "https://rpc-sentinel-ia.cosmosia.notional.ventures/",
        api_service: "https://api-sentinel-ia.cosmosia.notional.ventures/",
    },
    'umee-validator': {
        id: 29,
        address: 'umee1dmahqt84r9je3sqvljzjrttjj78cmrf39jndx6',
        valAddr: 'umeevaloper1dmahqt84r9je3sqvljzjrttjj78cmrf39k5zhs',
        key: 'umee',
        name: 'umee-validator',
        rpc_service: "https://rpc-umee-ia.cosmosia.notional.ventures/",
        api_service: "https://api-umee-ia.cosmosia.notional.ventures/",
    },
    'osmosis-relayer-grant-2022/6/7/8': {
        id: 18,
        address: 'osmo1kt4ectnx0mnhnhpx9z457q73ad26fm7qjd2yyx',
        key: 'osmosis',
        name: 'osmosis-relayer-grant-2022/6/7/8',
        rpc_service: "https://rpc-osmosis-ia.cosmosia.notional.ventures/",
        api_service: "https://api-osmosis-ia.cosmosia.notional.ventures/",
    },
    'osmosis-relayer-grant-2022/9/10/11': {
        id: 18,
        address: 'osmo1dvrte7mhjz0acrlm49d96gkeld0r282x0nxjgu',
        key: 'osmosis',
        name: 'osmosis-relayer-grant-2022/9/10/11',
        rpc_service: "https://rpc-osmosis-ia.cosmosia.notional.ventures/",
        api_service: "https://api-osmosis-ia.cosmosia.notional.ventures/",
    },
    'osmosis-relayer-grant-2022/12-2023/1/2': {
        id: 18,
        address: 'osmo1y4tcmgca8dvrqm7w4yx4x7wx8kp75ljkwqkqzp',
        key: 'osmosis',
        name: 'osmosis-relayer-grant-2022/12-2023/1/2',
        rpc_service: "https://rpc-osmosis-ia.cosmosia.notional.ventures/",
        api_service: "https://api-osmosis-ia.cosmosia.notional.ventures/",
    },
    'osmosis-grant-multisig': {
        id: 18,
        address: 'osmo1lxjj8ykacc2uh0s8t9d0zdesxaea790fv4hrp4',
        key: 'osmosis',
        name: 'osmosis-grant-multisig',
        rpc_service: "https://rpc-osmosis-ia.cosmosia.notional.ventures/",
        api_service: "https://api-osmosis-ia.cosmosia.notional.ventures/",
    },
    'evmos-airdrop': {
        id: 9,
        address: 'evmos1ckdsxugdxcja2mpc86uguzgvlknkctq275y6ne',
        key: 'evmos',
        name: 'evmos-airdrop',
        rpc_service: "https://rpc-evmos-ia.cosmosia.notional.ventures/",
        api_service: "https://api-evmos-ia.cosmosia.notional.ventures/",
    },
    'evmos-first-month-payment': {
        id: 9,
        address: 'evmos1wvp5vmcutt7meqspuykqkgsthvpea3u4djasw0',
        name: 'evmos-first-month-payment',
        rpc_service: "https://rpc-evmos-ia.cosmosia.notional.ventures/",
        api_service: "https://api-evmos-ia.cosmosia.notional.ventures/",
    },
    'evmos-second-month-payment': {
        id: 9,
        address: 'evmos1gthxyuc9nj92n7ggye6k0ufacmmd42ewqcdum4',
        key: 'evmos',
        name: 'evmos-second-month-payment',
        rpc_service: "https://rpc-evmos-ia.cosmosia.notional.ventures/",
        api_service: "https://api-evmos-ia.cosmosia.notional.ventures/",
    },
    'evmos-third-month-payment': {
        id: 9,
        address: 'evmos178pgzge6t6ldvzq04xfznxag63rvlaftnfc6mp',
        key: 'evmos',
        name: 'evmos-third-month-payment',
        rpc_service: "https://rpc-evmos-ia.cosmosia.notional.ventures/",
        api_service: "https://api-evmos-ia.cosmosia.notional.ventures/",
    },
}

module.exports.denomToId = {
    "akt": "akash-network",
    "btsg": "bitsong",
    "bcna": "bitcanna",
    "atom": "cosmos",
    "cheq": "cheqd-network",
    "huahua": "chihuahua-token",
    "boot": "bostrom",
    "ngm": "e-money",
    "evmos": "evmos",
    "fet": "fetch-ai",
    "inj": "injective-protocol",
    "ixo": "ixo",
    "juno": "juno-network",
    "kava": "kava",
    "xki": "ki",
    "darc": "darc",
    "osmo": "osmosis",
    "flix": "omniflix-network",
    "pasg": "pasg",
    "hash": "provenance-blockchain",
    "regen": "regen",
    "stars": "stargaze",
    "iov": "starname",
    "scrt": "secret",
    "strd": "stride",
    "statom": "stride-staked-atom",
    "dec": "decentr",
    "dvpn": "sentinel",
    "umee": "umee",
} 

module.exports.specialDenom = {
    boot: {
        denom: 'boot',
        exponent: 0
    },
    inj: {
        denom: 'inj',
        exponent: 18
    },
};
